const pubConferencesCoauthor = [
   {
    "authors": ["B. Gorry", "T. Fischer", "M. Milford", "A. Fontan"],
    "title": "UnderLoc: Image-Based Relocalization and Alignment for Long-Term Monitoring of Dynamic Underwater Environments",
    "venue": conferenceVenues["IROS"],
    "thumbimage": "underloc.png",
    "thumblink": "https://youtu.be/CYrg5-nY0Rw",
    "year": "2025",
    "pages": "Hangzhou, China, October",
    "links": [{"name": "Paper", "link": "https://arxiv.org/pdf/2503.04096"}, {"name": "Code", "link": "https://github.com/bev-gorry/underloc"}, {"name": "YouTube", "link": "https://youtu.be/CYrg5-nY0Rw"}, { "name": "IROS25", "link": "https://www.iros25.org/" }],
    "awards": ["Finalist for the IEEE-RAS Outstanding #WiRA Student Paper Award"]
  },
  // {
  //   "authors": ["M Windsor", "A. Fontan", "P Pivonka", "M. Milford"],
  //   "title": "Forward prediction of target localization failure through pose estimation artifact modelling",
  //   "venue": conferenceVenues["RA-L"],
  //   "thumbimage": "morgan.png",
  //   "thumblink": "https://arxiv.org/pdf/2311.02872",
  //   "year": "2024",
  //   "pages": "Vol. 9, No. 5, May",
  //   "links": [{"name": "Paper", "link": "https://ieeexplore.ieee.org/abstract/document/10480534/"}],
  // },  
  {
    "authors": ["S.T. Nguyen", "A. Fontan", "M. Milford", "T. Fischer"],
    "title": "FocusTune: Tuning Visual Localization through Focus-Guided Sampling",
    "venue": conferenceVenues["WACV"],
    "thumbimage": "focustune.png",
    "thumblink": "https://arxiv.org/pdf/2311.02872",
    "year": "2024",
    "pages": "Waikoloa, Hawaii, January",
    "links": [{"name": "Paper", "link": "https://openaccess.thecvf.com/content/WACV2024/html/Nguyen_FocusTune_Tuning_Visual_Localization_Through_Focus-Guided_Sampling_WACV_2024_paper.html"}, {"name": "Code", "link": "https://github.com/sontung/focus-tune"}],
  },  
  {
    "authors": ["L. Meyer", "M. Smíšek", "A. Fontan", "L. Oliva-Maza, D. Medina, M. J. Schuster, F. Steidle, M. Vayugundla, M. G. Müller, B. Rebele, A. Wedler, R. Triebel"],
    "title": "The MADMAX data set for visual‐inertial rover navigation on Mars",
    "venue": conferenceVenues["JFR"],
    "thumbimage": "madmax.png",
    "thumblink": "https://datasets.arches-projekt.de/morocco2018/",
    "year": "2021",
    "pages": "Wiley Online Library",
    "links": [{"name": "Paper", "link": "https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/rob.22016"}, {"name": "Dataset", "link": "https://datasets.arches-projekt.de/morocco2018/"}],
  },
  {
    "authors": ["I. Ballester", "A. Fontan", "J. Civera", "KH. Strobl", "R. Triebel"],
    "title": "DOT: Dynamic Object Tracking for Visual SLAM",
    "venue": conferenceVenues["ICRA"],
    "thumbimage": "dot.jpg",
    "thumblink": "https://youtu.be/9hWChyQGKJk",
    "year": "2021",
    "pages": "Xi'an, China, June",
    "links": [{"name": "Paper", "link": "https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9561452"}, {"name": "YouTube", "link": "https://youtu.be/9hWChyQGKJk"}, { "name": "ICRA21", "link": "https://ewh.ieee.org/soc/ras/conf/fullysponsored/icra/icra2021/icra2021/web.archive.org/web/20210531183741/https_/www.ieee-icra.org/index.html" }],
  },
  // {
  //   "authors": ["S. Looper", "J. Rodriguez-Puigvert", "R. Siegwart", "C. Cadena", "L. Schmid"],
  //   "title": "3D VSG: Long-term Semantic Scene Change Prediction through 3D Variable Scene Graphs",
  //   "venue": conferenceVenues["ICRA"],
  //   "thumbimage": "3DVSG.jpg",
  //   "thumblink": "https://github.com/ethz-asl/3d_vsg",
  //   "year": "2023",
  //   "pages": "London, UK, May",
  //   "links": [{ "name": "IEEE", "link": "https://ieeexplore.ieee.org/document/10161212" }, { "name": "ArXiv", "link": "https://arxiv.org/abs/2209.07896" }, { "name": "Code", "link": "https://github.com/ethz-asl/3d_vsg" }]
  // },
  // {
  //   "authors": ["L. Schmid", "J. Delmerico", "J. Schonberger", "J. Nieto", "M. Pollefeys", "R. Siegwart", "C. Cadena"],
  //   "title": "Panoptic Multi-TSDFs: a Flexible Representation for Online Multi-resolution Volumetric Mapping and Long-term Dynamic Scene Consistency",
  //   "venue": conferenceVenues["ICRA"],
  //   "thumbimage": "PM.jpg",
  //   "thumblink": "https://github.com/ethz-asl/3d_vsg",
  //   "year": "2022",
  //   "pages": "Philadelphia (PA), USA, May",
  //   "links": [{ "name": "IEEE", "link": "https://ieeexplore.ieee.org/document/9811877" }, { "name": "ArXiv", "link": "https://arxiv.org/abs/2109.10165" }, { "name": "Code", "link": "https://github.com/ethz-asl/panoptic_mapping" }, { "name": "Video", "link": "https://www.youtube.com/watch?v=A7o2Vy7_TV4" }]
  // },
  // {
  //   "authors": ["S. Lionar", "L. Schmid", "C. Cadena", "R. Siegwart", "A. Cramariuc"],
  //   "title": "NeuralBlox: Real-Time Neural Representation Fusion for Robust Volumetric Mapping",
  //   "venue": conferenceVenues["3DV"],
  //   "thumbimage": "Neuralblox.jpg",
  //   "thumblink": "https://github.com/ethz-asl/3d_vsg",
  //   "year": "2021",
  //   "pages": "London, United Kingdom, December",
  //   "links": [{ "name": "IEEE", "link": "https://ieeexplore.ieee.org/document/9665902" }, { "name": "ArXiv", "link": "https://arxiv.org/abs/2110.09415" }, { "name": "Code", "link": "https://github.com/ethz-asl/neuralblox" }],
  //   "sharedfirst": true
  // },
  // {
  //   "authors": ["T. Digumarti", "L. Schmid", "G. Rizzi", "J. Nieto", "R. Siegwart", "P. Beardsley", "C. Cadena"],
  //   "title": "An Approach for Semantic Segmentation of Tree-like Vegetation",
  //   "venue": conferenceVenues["ICRA"],
  //   "thumbimage": "TreeSeg.jpg",
  //   "thumblink": "https://ieeexplore.ieee.org/document/8793576",
  //   "year": "2019",
  //   "pages": "Montreal, Canada, May",
  //   "links": [{ "name": "IEEE", "link": "https://ieeexplore.ieee.org/document/8793576" }],
  //   "sharedfirst": true
  // }
]