const pubConferencesOther = [
  {
    "authors": ["A.D. Hines", "A. Fontan", "M. Milford", "T. Fischer"],
    "title": "Event-LAB: Towards Standardized Evaluation of Neuromorphic Localization Methods",
    "venue": conferenceVenues["arXiv"],
    "thumbimage": "Event-LAB.png",
    "thumblink": "https://github.com/EventLAB-Team/Event-LAB",
    "year": "2025",
    "pages": "Brisbane, Australia, September",
    "links": [{"name": "Paper", "link": "https://arxiv.org/abs/2509.14516"}, {"name": "Code", "link": "https://github.com/EventLAB-Team/Event-LAB"}],
  },
  {
    "authors": ["G.B. Nair", "A. Fontan", "M. Milford", "T. Fischer"],
    "title": "Event-Based Visual Teach-and-Repeat via Fast Fourier-Domain Cross-Correlation",
    "venue": conferenceVenues["arXiv"],
    "thumbimage": "event_teach.png",
    "thumblink": "https://arxiv.org/abs/2509.17287",
    "year": "2025",
    "pages": "Brisbane, Australia, September",
    "links": [{"name": "Paper", "link": "https://arxiv.org/abs/2509.17287"}],
  },
  {
    "authors": ["S.T. Nguyen", "A. Fontan", "M. Milford", "T. Fischer"],
    "title": "FUSELOC: Fusing Global and Local Descriptors to Disambiguate 2D-3D Matching in Visual Localization",
    "venue": conferenceVenues["ICCV-WS"],
    "thumbimage": "fuseloc.png",
    "thumblink": "https://arxiv.org/pdf/2311.02872",
    "year": "2025",
    "pages": "Waikoloa, Hawaii, October",
    "links": [{"name": "Paper", "link": "https://openaccess.thecvf.com/content/ICCV2025W/CALIPOSE/papers/Nguyen_FUSELOC_Fusing_Global_and_Local_Descriptors_for_Fast_and_Robust_ICCVW_2025_paper.pdf"}, {"name": "Code", "link": "https://github.com/sontung/descriptor-disambiguation"}],
  }, 
  {
    "authors": ["A. Fontan", "J. Civera", "M. Milford"],
    "title": "Adaptive Outlier Thresholding for Bundle Adjustment in Visual SLAM",
    "venue": conferenceVenues["ICRA"],
    "thumbimage": "adaptiveoutlier.png",
    "thumblink": "https://ieeexplore.ieee.org/abstract/document/10610433",
    "year": "2024",
    "pages": "London, UK, May",
    "links": [{"name": "Paper", "link": "https://ieeexplore.ieee.org/abstract/document/10610433"}],
  }, 
  {
    "authors": ["M. Windsor", "A. Fontan", "P. Pivonka", "M. Milford"],
    "title": "Forward prediction of target localization failure through pose estimation artifact modelling",
    "venue": conferenceVenues["RA-L"],
    "thumbimage": "morgan.png",
    "thumblink": "https://ieeexplore.ieee.org/abstract/document/10480534",
    "year": "2024",
    "pages": "ICRA, London, UK, May",
    "links": [{"name": "Paper", "link": "https://ieeexplore.ieee.org/abstract/document/10480534"}],
  },
  {
    "authors": ["S.T. Nguyen", "A. Fontan", "M. Milford", "T. Fischer"],
    "title": "FocusTune: Tuning Visual Localization through Focus-Guided Sampling",
    "venue": conferenceVenues["WACV"],
    "thumbimage": "focustune.png",
    "thumblink": "https://arxiv.org/pdf/2311.02872",
    "year": "2024",
    "pages": "Waikoloa, Hawaii, January",
    "links": [{"name": "Paper", "link": "https://openaccess.thecvf.com/content/WACV2024/html/Nguyen_FocusTune_Tuning_Visual_Localization_Through_Focus-Guided_Sampling_WACV_2024_paper.html"}, {"name": "Code", "link": "https://github.com/sontung/focus-tune"}],
  },  
  {
    "authors": ["A. Fontan", "J. Civera", "M. Milford"],
    "title": "Motion-Bias-Free Feature-Based SLAM",
    "venue": conferenceVenues["BMVC"],
    "thumbimage": "motionbias.png",
    "thumblink": "https://papers.bmvc2023.org/0741.pdf",
    "year": "2023",
    "pages": "Aberdeen, UK, November",
    "links": [{"name": "Paper", "link": "https://papers.bmvc2023.org/0741.pdf"}],
  },  
  {
    "authors": ["A. Fontan","R. Giubilato", "L. Oliva", "J. Civera", "R. Triebel"],
    "title": "SID-SLAM: Semi-Direct Information-Driven RGB-D SLAM",
    "venue": conferenceVenues["RA-L"],
    "thumbimage": "sidslam.png",
    "thumblink": "https://ieeexplore.ieee.org/abstract/document/10058038",
    "year": "2023",
    "pages": "ICRA, Detroit, USA, October",
    "links": [{"name": "Paper", "link": "https://ieeexplore.ieee.org/abstract/document/10058038"}],
  },
  {
    "authors": ["A. Fontan", "L. Oliva", "J. Civera", "R. Triebel"],
    "title": "Model for Multi-View Residual Covariances Based on Perspective Deformation",
    "venue": conferenceVenues["RA-L"],
    "thumbimage": "multiviewdeformation.jpg",
    "thumblink": "https://youtu.be/ztbqIU-bEZY",
    "year": "2022",
    "pages": "ICRA, Philadelphia, USA, May",
    "links": [{"name": "Paper", "link": "https://ieeexplore.ieee.org/abstract/document/9681286"}, {"name": "Youtube", "link": "https://youtu.be/ztbqIU-bEZY"}],
  },
  // {
  //   "authors": ["S. Looper", "J. Rodriguez-Puigvert", "R. Siegwart", "C. Cadena", "L. Schmid"],
  //   "title": "3D VSG: Long-term Semantic Scene Change Prediction through 3D Variable Scene Graphs",
  //   "venue": conferenceVenues["ICRA"],
  //   "thumbimage": "3DVSG.jpg",
  //   "thumblink": "https://github.com/ethz-asl/3d_vsg",
  //   "year": "2023",
  //   "pages": "London, UK, May",
  //   "links": [{ "name": "IEEE", "link": "https://ieeexplore.ieee.org/document/10161212" }, { "name": "ArXiv", "link": "https://arxiv.org/abs/2209.07896" }, { "name": "Code", "link": "https://github.com/ethz-asl/3d_vsg" }]
  // },
  // {
  //   "authors": ["L. Schmid", "J. Delmerico", "J. Schonberger", "J. Nieto", "M. Pollefeys", "R. Siegwart", "C. Cadena"],
  //   "title": "Panoptic Multi-TSDFs: a Flexible Representation for Online Multi-resolution Volumetric Mapping and Long-term Dynamic Scene Consistency",
  //   "venue": conferenceVenues["ICRA"],
  //   "thumbimage": "PM.jpg",
  //   "thumblink": "https://github.com/ethz-asl/3d_vsg",
  //   "year": "2022",
  //   "pages": "Philadelphia (PA), USA, May",
  //   "links": [{ "name": "IEEE", "link": "https://ieeexplore.ieee.org/document/9811877" }, { "name": "ArXiv", "link": "https://arxiv.org/abs/2109.10165" }, { "name": "Code", "link": "https://github.com/ethz-asl/panoptic_mapping" }, { "name": "Video", "link": "https://www.youtube.com/watch?v=A7o2Vy7_TV4" }]
  // },
  // {
  //   "authors": ["S. Lionar", "L. Schmid", "C. Cadena", "R. Siegwart", "A. Cramariuc"],
  //   "title": "NeuralBlox: Real-Time Neural Representation Fusion for Robust Volumetric Mapping",
  //   "venue": conferenceVenues["3DV"],
  //   "thumbimage": "Neuralblox.jpg",
  //   "thumblink": "https://github.com/ethz-asl/3d_vsg",
  //   "year": "2021",
  //   "pages": "London, United Kingdom, December",
  //   "links": [{ "name": "IEEE", "link": "https://ieeexplore.ieee.org/document/9665902" }, { "name": "ArXiv", "link": "https://arxiv.org/abs/2110.09415" }, { "name": "Code", "link": "https://github.com/ethz-asl/neuralblox" }],
  //   "sharedfirst": true
  // },
  // {
  //   "authors": ["T. Digumarti", "L. Schmid", "G. Rizzi", "J. Nieto", "R. Siegwart", "P. Beardsley", "C. Cadena"],
  //   "title": "An Approach for Semantic Segmentation of Tree-like Vegetation",
  //   "venue": conferenceVenues["ICRA"],
  //   "thumbimage": "TreeSeg.jpg",
  //   "thumblink": "https://ieeexplore.ieee.org/document/8793576",
  //   "year": "2019",
  //   "pages": "Montreal, Canada, May",
  //   "links": [{ "name": "IEEE", "link": "https://ieeexplore.ieee.org/document/8793576" }],
  //   "sharedfirst": true
  // }
]